/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.auraboutique.email;

/**
 *
 * @author 0ENNO
 */
public class EmailMainGUI extends javax.swing.JFrame {

    /**
     * Creates new form EmailMainGUI
     */
    public EmailMainGUI() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Email");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        MsgText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ToEmail = new javax.swing.JTextField();
        CcEmail = new javax.swing.JTextField();
        SendButton = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 450));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MsgText.setForeground(new java.awt.Color(255, 204, 102));
        MsgText.setOpaque(false);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 204, 102));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        MsgText.setViewportView(jTextArea1);

        getContentPane().add(MsgText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 790, 250));

        ToEmail.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        ToEmail.setForeground(new java.awt.Color(255, 255, 255));
        ToEmail.setBorder(null);
        ToEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        ToEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToEmailActionPerformed(evt);
            }
        });
        getContentPane().add(ToEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 710, 30));

        CcEmail.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        CcEmail.setForeground(new java.awt.Color(255, 255, 255));
        CcEmail.setBorder(null);
        CcEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        CcEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcEmailActionPerformed(evt);
            }
        });
        getContentPane().add(CcEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 710, 40));
        getContentPane().add(SendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 160, 50));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseMouseReleased(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 30, 40));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/auraboutique/images/mail_test.png"))); // NOI18N
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 880, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void CloseMouseReleased(java.awt.event.MouseEvent evt) {                                    
        System.exit(0);
    }                                   

    private void ToEmailActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void CcEmailActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel BackGround;
    private javax.swing.JTextField CcEmail;
    private javax.swing.JLabel Close;
    private javax.swing.JScrollPane MsgText;
    private javax.swing.JLabel SendButton;
    private javax.swing.JTextField ToEmail;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
